<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Description>A structured, cross-platform .NET API for image processing with bundled libvips command-line distributions.</Description>
        <Version Condition="'$(BUILD_VERSION)' == ''">4.0.0</Version>
        <Version Condition="'$(BUILD_VERSION)' != ''">$(BUILD_VERSION)</Version>
        <AssemblyName>Soenneker.Libvips.Util</AssemblyName>
        <PackageId>Soenneker.Libvips.Util</PackageId>
        <PackageTags>libvips util image processing avif webp cross-platform native libvipsutil csharp dotnet c# .net</PackageTags>
        <Copyright>Copyright © 2026 Jake Soenneker</Copyright>
        <Authors>Jake Soenneker</Authors>
        <Company>https://soenneker.com</Company>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/soenneker/soenneker.libvips.util</PackageProjectUrl>
        <RepositoryUrl>https://github.com/soenneker/soenneker.libvips.util</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <LangVersion>latest</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Soenneker.Gen.EnumValues" Version="4.0.46" />
        <PackageReference Include="Soenneker.Asyncs.Locks" Version="4.0.76" />
        <PackageReference Include="Soenneker.Libvips.Linux" Version="4.0.24" PrivateAssets="analyzers;build" />
        <PackageReference Include="Soenneker.Libvips.Windows" Version="4.0.8" PrivateAssets="analyzers;build" />
        <PackageReference Include="Soenneker.Utils.Directory" Version="4.0.916" />
        <PackageReference Include="Soenneker.Utils.File" Version="4.0.2246" />
        <PackageReference Include="Soenneker.Utils.Path" Version="4.0.1209" />
        <PackageReference Include="Soenneker.Utils.Process" Version="4.0.1534" />
        <PackageReference Include="Soenneker.Utils.Paths.Resources" Version="4.0.229" />
        <PackageReference Include="Soenneker.Utils.PooledStringBuilders" Version="4.0.29" />
        <PackageReference Include="Soenneker.Utils.Runtime" Version="4.0.1086" />
    </ItemGroup>
</Project>
 
